name 'cookbooks'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures cookbooks'
long_description 'Installs/Configures cookbooks'
version '0.1.0'
